Repository prgrms-fe-devcourse/NFE1-1-3-MOODI, pull requests merged in 2024-10, with the labels that each got.

#5 chore : 상대경로 설정 완료
  tsconfig.json
Labels: 🔧env

#20 feat : 스토리북 개발 환경 구축 완료
  .github/issue_template.md
  .github/pull_request_template.md
  .github/workflows/deploy.yml
  .prettierignore
  .prettierrc
  .storybook/main.ts
  .storybook/preview.ts
  .vscode/funcitionComponent.tsx.code-snippets
  .vscode/styled.tsx.code-snippets
  bable.config.js
  eslint.config.mjs
  package.json
  public/index.html
  src/App.tsx
  src/app/App.tsx
  src/app/Index.tsx
  src/app/styles/globalStyles.ts
  src/widgets/header/ui/Header.styled.tsx
  src/widgets/header/ui/Header.tsx
  tsconfig.json
  webpack.common.js
  webpack.config.js
  webpack/webpack.dev.js
  webpack/webpack.prod.js
Labels: 🔧env

#26 chore : 프리티어, 스토리북 설정 변경
  .prettierrc
  .storybook/main.ts
Labels: ✏️chore

#23 feat : 스타일 설정 객체 추가
  src/app/styles/styled.d.ts
  src/app/styles/theme.ts
Labels: 🎨style

#24 feat : 공개/비공개 버튼 컴포넌트 추가
  public/private.svg
  public/public.svg
  src/feature/diary-wirte/model/type.tsx
  src/feature/diary-wirte/ui/VisibilityButton.stories.tsx
  src/feature/diary-wirte/ui/VisibilityButton.styled.tsx
  src/feature/diary-wirte/ui/VisibilityButton.tsx
Labels: ✨feature

#28 chore : 헤더 import 수정
  src/widgets/header/ui/Header.tsx
Labels: ✏️chore

#35 feat : 공개/비공개 버튼 컨테이너 작성
  src/feature/diary-wirte/ui/VisibilityButton.tsx
  src/feature/diary-write/index.ts
  src/feature/diary-write/model/type.tsx
  src/feature/diary-write/ui/VisibilityButton.stories.tsx
  src/feature/diary-write/ui/VisibilityButton.styled.tsx
  src/feature/diary-write/ui/VisibilityButton.tsx
  src/widgets/diary-visibility-controls/index.tsx
  src/widgets/diary-visibility-controls/model/type.tsx
  src/widgets/diary-visibility-controls/ui/DiaryVisibilityControls.stories.tsx
  src/widgets/diary-visibility-controls/ui/DiaryVisibilityControls.styled.tsx
  src/widgets/diary-visibility-controls/ui/DiaryVisibilityControls.tsx
  src/widgets/header/ui/Header.tsx
Labels: ✨feature

#34 feat : 공유 컴포넌트 버튼 개발
  src/shared/ui/Button/Button.stories.tsx
  src/shared/ui/Button/Button.styled.tsx
  src/shared/ui/Button/Button.tsx
Labels: ✨feature

#40 feat : 기분 선택 버튼 컴포넌트 작성
  src/entities/emotion/index.ts
  src/entities/emotion/model/type.ts
  src/entities/emotion/ui/EmotionButton.stories.tsx
  src/entities/emotion/ui/EmotionButton.styled.tsx
  src/entities/emotion/ui/EmotionButton.tsx
  src/feature/diary-write/emotion/model/type.ts
  src/feature/diary-write/emotion/ui/EmotionButtonGroup.stories.tsx
  src/feature/diary-write/emotion/ui/EmotionButtonGroup.styled.tsx
  src/feature/diary-write/emotion/ui/EmotionButtonGroup.tsx
  src/feature/diary-write/index.ts
  src/feature/diary-write/visibility/model/type.tsx
  src/feature/diary-write/visibility/ui/VisibilityButton.stories.tsx
  src/feature/diary-write/visibility/ui/VisibilityButton.styled.tsx
  src/feature/diary-write/visibility/ui/VisibilityButton.tsx
Labels: ✨feature

#49 fix : 공유 컴포넌트 타입 분리 및 오류 수정
  src/shared/ui/Button/Button.styled.tsx
  src/shared/ui/Button/Button.tsx
  src/shared/ui/Button/Button.types.ts
Labels: 🐛 fix

#58 chore : 공유 컴포넌트 버튼 border-radius속성 추가
  src/shared/ui/Button/Button.stories.ts
  src/shared/ui/Button/Button.styled.ts
  src/shared/ui/Button/Button.tsx
  src/shared/ui/Button/Button.types.ts
Labels: ✏️chore

#61 feat : 달력컴포넌트 개발 1차
  package.json
  public/calendar_plus.svg
  public/emoji/emoji_blank.svg
  public/emoji/emoji_grateful.svg
  src/app/App.tsx
  src/features/calendar/calendar-logic/calendarDataFetch.tsx
  src/features/calendar/calendar-logic/calendarLogic.tsx
  src/features/calendar/calendar-ui/CalendarUi.tsx
  src/features/calendar/calendar-ui/calendarUiCss.ts
  src/features/calendar/get-emotion-path/getEmotionPath.ts
  src/features/calendar/index.tsx
  src/features/calendar/indexCss.ts
  yarn.lock
Labels: ✨feature

#59 feat : 랜딩페이지 부분 완성
  src/pages/LandingPage/index.ts
  src/pages/LandingPage/ui/LandingTitle/LandingTitle.stories.ts
  src/pages/LandingPage/ui/LandingTitle/LandingTitle.styled.ts
  src/pages/LandingPage/ui/LandingTitle/LandingTitle.tsx
  src/pages/LandingPage/ui/Page/Page.stories.ts
  src/pages/LandingPage/ui/Page/Page.styled.ts
  src/pages/LandingPage/ui/Page/Page.tsx
  src/pages/LandingPage/ui/SubTitle/SubTitle.stories.ts
  src/pages/LandingPage/ui/SubTitle/SubTitle.styled.ts
  src/pages/LandingPage/ui/SubTitle/SubTitle.tsx
Labels: ✨feature

#62 feat : moveTopButton 구현
  public/arrow_up.svg
  src/shared/ui/MoveTopButton/MoveTopButton.stories.tsx
  src/shared/ui/MoveTopButton/MoveTopButton.styled.ts
  src/shared/ui/MoveTopButton/MoveTopButton.tsx
Labels: ✨feature

#67 feat : KeywordButton 컴포넌트 구현
  src/entities/KeywordButton/index.ts
  src/entities/KeywordButton/model/type.ts
  src/entities/KeywordButton/ui/KeywordButton.stories.ts
  src/entities/KeywordButton/ui/KeywordButton.styled.ts
  src/entities/KeywordButton/ui/KeywordButton.tsx
Labels: ✨feature

#70 feat : 일기 리스트 아이템 컴포넌트 UI 개발
  eslint.config.mjs
  src/features/diary-list-item/diary-list-item-type/DiaryListItemType.ts
  src/features/diary-list-item/diary-list-item-ui/content-box/ContentBox.tsx
  src/features/diary-list-item/diary-list-item-ui/content-box/ContentBoxCss.ts
  src/features/diary-list-item/diary-list-item-ui/image-box/ImageBox.tsx
  src/features/diary-list-item/diary-list-item-ui/image-box/ImageBoxCss.ts
  src/features/diary-list-item/diary-list-item-ui/index.tsx
  src/features/diary-list-item/diary-list-item-ui/indexCss.ts
  src/features/diary-list-item/index.tsx
  src/pages/MainPage/index.tsx
  src/shared/model/getEmotionPath.ts
Labels: ✨feature

#71 feat : modal 컴포넌트 구현 완료
  package.json
  src/entities/chart/ui/Chart.stories.tsx
  src/shared/hooks/useModal.tsx
  src/shared/ui/Modal/Modal.stories.tsx
  src/shared/ui/Modal/Modal.styled.ts
  src/shared/ui/Modal/Modal.tsx
  src/shared/ui/Overlay/Overlay.stories.tsx
  src/shared/ui/Overlay/Overlay.styled.tsx
  src/shared/ui/Overlay/Overlay.tsx
  yarn.lock
Labels: ✨feature

#77 fix : EmotionButtonList 컴포넌트 (대표/서브 감정 선택 옵션 추가)
  src/shared/EmotionButton/ui/EmotionButton.tsx
  src/shared/EmotionButtonList/ui/EmotionButtonList.stories.tsx
  src/shared/EmotionButtonList/ui/EmotionButtonList.styled.ts
  src/shared/EmotionButtonList/ui/EmotionButtonList.tsx
  src/shared/EmotionList/ui/EmotionButtonList.stories.tsx
  src/shared/EmotionList/ui/EmotionButtonList.tsx
Labels: 🐛 fix

#79 fix : keywordbutton타입과 스타일 수정
  src/entities/KeywordButton/model/type.ts
  src/entities/KeywordButton/ui/KeywordButton.styled.ts
Labels: 🐛 fix

#80 feat : 일기 작성 페이지 음악 선택 기능
  .storybook/preview-head.html
  .storybook/preview.ts
  package.json
  public/index.html
  public/mockServiceWorker.js
  src/entities/music/api/fetchMusicList.ts
  src/entities/music/hooks/useSearchMusic.ts
  src/entities/music/index.ts
  src/entities/music/model/type.ts
  src/entities/music/model/useMusicStore.ts
  src/entities/music/ui/EmptyMusicCard.styled.tsx
  src/entities/music/ui/EmptyMusicCard.tsx
  src/entities/music/ui/MusicCard.stories.tsx
  src/entities/music/ui/MusicCard.styled.tsx
  src/entities/music/ui/MusicCard.tsx
  src/features/diary-write/index.ts
  src/features/diary-write/music-search-input/model/type.ts
  src/features/diary-write/music-search-input/ui/MusicSearchInput.styled.tsx
  src/features/diary-write/music-search-input/ui/MusicSearchInput.tsx
  src/features/diary-write/musicList/model/type.ts
  src/features/diary-write/musicList/ui/MusicCardList.stories.tsx
  src/features/diary-write/musicList/ui/MusicCardList.styled.tsx
  src/features/diary-write/musicList/ui/MusicCardList.tsx
  src/features/diary-write/search-mode-selector/model/type.ts
  src/features/diary-write/search-mode-selector/ui/SearchModeButtonGroup.stories.tsx
  src/features/diary-write/search-mode-selector/ui/SearchModeButtonGroup.styled.tsx
  src/features/diary-write/search-mode-selector/ui/SearchModeButtonGroup.tsx
  src/shared/api/mocks/handlers.ts
  src/shared/ui/InputForm/InputForm.styled.tsx
  src/shared/ui/InputForm/InputForm.tsx
  src/shared/ui/InputForm/InputForm.types.tsx
  src/widgets/select-music/ui/SelectMusicContainer.stories.tsx
  src/widgets/select-music/ui/SelectMusicContainer.styled.tsx
  src/widgets/select-music/ui/SelectMusicContainer.tsx
  yarn.lock
Labels: 🔧env, ✨feature, 🐛 fix, 🎨style, ✏️chore

#81 chore : 일기 리스트 아이템 컴포넌트 개발 완료
  src/features/diary-list-item/diary-list-item-type/DiaryListItemType.ts
  src/features/diary-list-item/diary-list-item-ui/content-box/ContentBox.tsx
  src/features/diary-list-item/diary-list-item-ui/image-box/ImageBox.tsx
  src/features/diary-list-item/diary-list-item-ui/image-box/ImageBoxCss.ts
  src/features/diary-list-item/diary-list-item-ui/index.tsx
  src/features/diary-list-item/diary-list-item-ui/indexCss.ts
  src/pages/MainPage/index.tsx
Labels: ✏️chore

#84 feat : api 캐싱 추가
  eslint.config.mjs
  src/entities/music/api/fetchMusicList.ts
  src/entities/music/hooks/useMusicSearch.ts
  src/entities/music/hooks/useSearchMusic.ts
  src/entities/music/index.ts
  src/features/diary-write/index.ts
  src/features/diary-write/musicList/ui/MusicCardList.tsx
  src/shared/EmotionButtonList/ui/EmotionButtonList.stories.tsx
  src/widgets/select-music/ui/SelectMusicContainer.tsx
Labels: ✨feature

#85 feat : 감정 키워드 선택 구현
  src/features/diary-write/emotion/model/type.ts
  src/features/diary-write/emotion/ui/EmotionButtonGroup.stories.ts
  src/features/diary-write/emotion/ui/EmotionButtonGroup.styled.ts
  src/features/diary-write/emotion/ui/EmotionButtonGroup.tsx
Labels: ✨feature

#87 fix : EmotionButtonGroup 타입 오류 수정
  src/features/diary-write/emotion/ui/EmotionButtonGroup.tsx
Labels: 🐛 fix

#88 64 feat toast 컴포넌트를 구현
  src/app/App.tsx
  src/features/Toast/hooks/useToastStore.ts
  src/features/Toast/model/type.ts
  src/features/Toast/ui/Toast.stories.ts
  src/features/Toast/ui/Toast.styeld.ts
  src/features/Toast/ui/Toast.tsx
  src/features/Toast/ui/ToastContainer.tsx
  src/features/Toast/ui/toastContainer.styled.tsx
  src/shared/ui/Modal/Modal.styled.ts
Labels: ✨feature

#93 feat : scroll event에 사용할 dot 구현 완료
  package.json
  src/entities/chart/ui/Chart.stories.tsx
  src/entities/scroll-dot-container/model/type.ts
  src/entities/scroll-dot-container/ui/ScrollDotContainer.stories.tsx
  src/entities/scroll-dot-container/ui/ScrollDotContainer.tsx
  src/entities/scroll-dot-container/ui/SrollDotContainer.styled.ts
  src/features/chart/ui/EmotionChart.tsx
  src/shared/api/mocks/handlers.ts
  src/shared/ui/ScrollDot/ScrollDot.stories.tsx
  src/shared/ui/ScrollDot/ScrollDot.styled.tsx
  src/shared/ui/ScrollDot/ScrollDot.tsx
  src/shared/ui/ScrollDot/ScrollDot.type.ts
Labels: ✨feature

#98 fix : 키워드 선택 오류 수정
  src/features/diary-write/emotion/ui/EmotionButtonGroup.tsx
Labels: 🐛 fix
